#!/usr/bin/env bash
set -e

echo "set project directory"
cd "$(dirname "$(readlink -f "$0")")"
cd ".."

export PATH="$HOME/.local/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
. $NVM_DIR/nvm.sh

echo "--> Setting node version"
nvm use

echo "--> Installing libraries"
export NODE_ENV="development"
yarn install
export NODE_ENV="production"

echo "Fetching languages"
yarn transifex:pull

echo "--> Building assets"
yarn build

if pm2 describe otp-portal > /dev/null; then
  echo "--> Restarting application"
  pm2 restart otp-portal --update-env
else
  echo "--> Setting up a new application"
  pm2 start index.js --name otp-portal
  sudo env PATH=$PATH:/home/ubuntu/.nvm/versions/node/$(node -v)/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
  pm2 save
fi
