#!/usr/bin/env bash
set -e

echo "set project directory"
cd "$(dirname "$(readlink -f "$0")")"
cd ".."

export PATH="$HOME/.local/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
. $NVM_DIR/nvm.sh

echo "--> Setting node version"
nvm use

echo "--> Installing libraries"
export NODE_ENV="development"
yarn install || exit
export NODE_ENV="production"

echo "Fetching languages"
yarn transifex:pull || exit

echo "--> Building assets"
BUILD_DIR=temp_build yarn build || exit

if [ ! -d "temp_build" ]; then
  echo '\033[31m Temp build Directory not exists!\033[0m'
  exit 1;
fi

rm -rf .next
mv temp_build .next

if pm2 describe otp-portal > /dev/null; then
  echo "--> Restarting application"
  pm2 restart ecosystem.config.js --update-env
else
  echo "--> Setting up a new application"
  pm2 start ecosystem.config.js
  sudo env PATH=$PATH:/home/ubuntu/.nvm/versions/node/$(node -v)/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
  pm2 save
fi

pm2 reset all

echo "Deploy done successfully"
